### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by SirNate0** [gengyong/luaaa#13]
Is inheritance supported? E.g. binding something like.
```
class Animal { ... };
class Cat: public Animal { ... };
class Tiger: public Cat { ... };

void AddToZoo(Animal& animal); // Should be callable with a Cat or a Tiger
```

**Comment by gengyong** [comment]
Yes.

**Comment by SirNate0** [comment]
Could you explain how to do that? When I try it with just the Animal and Cat ("AwesomeCat" in Lua as in the example code), and a `void ZooSound(Animal& a)` function I get the followign error:
```
lua err: [string "console"]:5: calling 'sound' on bad self (cpp class `6Animal` not export)Cat: cat[0x4105af40] AwesomeKitty is free.
```

**Comment by gengyong** [comment]
could you please post your codes here?

**Comment by andrsd** [comment]
I am interested in this too. This is the code I am using. I take your `Cat` class and inherit from it like so:
```
class SpecialCat : public Cat
{
public:
  SpecialCat() : Cat("cat") { printf("SpecialCat\n"); }
};
```
Then, I add the registration:
```
  LuaClass<SpecialCat>(L, "SpecialCat").ctor<>();
```
And in the lua file, I do:
```
b = SpecialCat.new()
b:setAge(5)
```
I can see the  printout from the constructor, but then an error message:
```
attempt to call a nil value (method 'setAge')
```

I suspect that the way I register `SpecialCat` is not correct. I would expect to tell the constructor what is the base class of "SpecialCat".

Any help with this would be highly appreciated.

**Comment by gengyong** [comment]
@andrsd 
please export setAge() method for SpecialCat:

````cpp
LuaClass<SpecialCat>(L, "SpecialCat").ctor().fun("setAge", &SpecialCat::setAge);
````

then "setAge" method can be call from lua.
