### ISSUE TITLE
Can I use std::function for callbacks?

### ISSUE THREAD

**Issue by NI-LAm** [gengyong/luaaa#14]
I have a C++ class I want to export to LUA. This class has a hashmap that maps a name to `std::function`. Currently I typically put lamdba expressions in there.
I now want to allow LUA to add values to this hashmap. To experiment a little bit I modified the example.cpp to accept a `std::function` with the same argument list in the testCallback function. This compiles fine but when I run this LUA complains:

`lua err: [string "console"]:103: bad argument #1 to 'testCallback' (cpp class ``St8functionIFiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEifEE`` not export)
`

Is it possible with luaaa to use `std::function` instead of function pointers?

**Comment by gengyong** [comment]
not supported yet.
 that's a good idea, I'll try if I can implement it in next week.

**Comment by gengyong** [comment]
this feature done in new version, please pull latest changes.

there is an example function 'testCallbackFunctor()' in example.cpp, which shows how to use std::function as callback.

and lambda can be exported to Lua now, to export lambda function:
```cpp
mod.fun("lambdaFunc", [](int a, int b) -> int {
    return a * b;
});
```

**Comment by NI-LAm** [comment]
Awesome. I created a pull request, to show that this works in both directions. One can also pass a LUA function to a C++ call that expects a std::function.
