### ISSUE TITLE
Need a little bit help

### ISSUE THREAD

**Issue by vega0** [gengyong/luaaa#2]
For static methods the same .fun calls?

**Comment by gengyong** [comment]
Yes.

**Comment by rusefillc** [comment]
Wow perfect timing I had more or less same example!

@gengyong any change to add static method example into official documentation? Maybe static getInstance() method for example?

**Comment by rusefillc** [comment]
@gengyong 
```
2021-09-23_19_08_09_748: EngineState: confirmation_luareset:8
2021-09-23_19_08_09_831: EngineState: LUA loading script length: 228...
2021-09-23_19_08_09_831: EngineState: LUA ERROR loading script: [string "t = Timer.new();..."]:2: field 'getInstance' is not callable (a nil value)
2021-09-23_19_08_09_833: EngineState: LUA: Tearing down instance...
```
how comes getInstance is a field? what part is nil? One day I will know.

**Comment by gengyong** [comment]
@rusefillc 
1. there is a typo in your code:
luaEngine.fun("getInsance") should be "getInstance".
2. static_cast<> in binding code is not required, template traits could resolve its type, so just declare binding as below:
luaEnging.fun("getInstance", &Engine::getInstance)...
and so on.

**Comment by rusefillc** [comment]
progress. error message has changed :) there is also a huge change that I am missing a lot in Lua syntax.

```
e = Engine.getInstance();
```
gives me
```
2021-09-23_20_04_23_208: EngineState: LUA loading script length: 48...
2021-09-23_20_04_23_208: EngineState: LUA ERROR loading script: [string "e = Engine.getInstance();..."]:1: field 'getInstance' is not callable (a nil value)
2021-09-23_20_04_23_208: EngineState: LUA: Tearing down instance...
```


while

```
e = Engine:getInstance();
```
starts to refer to method
```
2021-09-23_20_06_56_461: EngineState: LUA loading script length: 48...
2021-09-23_20_06_56_461: EngineState: LUA ERROR loading script: [string "e = Engine:getInstance();..."]:1: method 'getInstance' is not callable (a nil value)
2021-09-23_20_06_56_461: EngineState: LUA: Tearing down instance...
```

**Comment by mck1117** [comment]
@gengyong I think @rusefillc's question is a bit more general one: in case of a singleton object in c++ land, what's the best way to use luaaa to get a handle to that object?

**Comment by mck1117** [comment]
An alternative could be if there's an easy enough way to return a luaaa object from a "standard" Lua hook (create some lua function `getMyObject()` that returns a luaaa-backed object).

**Comment by rusefillc** [comment]
@mck1117 is that relevant here, is not Class.getInstance() just a normal static method?

**Comment by gengyong** [comment]
Lua class means it"s member should be access from an instance,  here if "Engine" was export as LuaClass, to access its member, an "Engine" instance should be created first, even the member function is binding with a C++ static function. if no "ctor" function was exported, a default lua "new" method(which was bound to the C++ default constructor) can create such an instance.

another methed is exported it as LuaModule, which was registered to global scope and don't require a instance to call it member. for singleton class XXX, you can exported instance as below:
LuaModule(luaState).fun("getXXXInstance", &XXX:getInstance)
and in lua call it from global scope.

**Comment by mck1117** [comment]
What's the recommended way to handle an object that needs a custom `getInstance()` (or equivalent) instead of using placement-new (whether with parameters or not) as is default for luaaa?

**Comment by gengyong** [comment]
and of course the LuaModule can be exported with a name, for example LuaModule(l, "engine").fun("getInstance", &Engine:getInstance), then from lua you can access it by engine.getInstance().

anyway the best solution is that export C++ static member function to Lua static member function instead of Lua member function, I'll have a try in recent future.

**Comment by mck1117** [comment]
> and of course the LuaModule can be exported with a name, for example LuaModule(l, "engine").fun("getInstance", &Engine:getInstance), then from lua you can access it by engine.getInstance().

Sure, I get this part, but how do you return a fully formed `Engine` object (native pointer stored, functions fleshed out, etc) from that `engine.getInstance()` function?

**Comment by gengyong** [comment]
@mck1117 export the static instance function in LuaModule.

**Comment by rusefillc** [comment]
```
LuaModule(l).fun("getEngineInstance", &Engine::getInstance);
```

```
e = getEngineInstance()
rpm = e:getRpmCalculator()
```

gives me

```
2021-09-23_21_21_24_245: EngineState: LUA loading script length: 118...
2021-09-23_21_21_24_245: EngineState: LUA ERROR loading script: [string "e = getEngineInstance()..."]:2: attempt to index a userdata value (global 'e')
2021-09-23_21_21_24_245: EngineState: LUA: Tearing down instance...
```

**Comment by gengyong** [comment]
> > and of course the LuaModule can be exported with a name, for example LuaModule(l, "engine").fun("getInstance", &Engine:getInstance), then from lua you can access it by engine.getInstance().
> 
> Sure, I get this part, but how do you return a fully formed `Engine` object (native pointer stored, functions fleshed out, etc) from that `engine.getInstance()` function?

good question.
I'm stunned🤦‍♂️.
yes you are right it doesnot work, a native engine instance is not what we expected here.  so the only method is declare a named 'ctor' for LuaClass, for example:
LuaClass<Engine>(l, "engine").ctor("getInstance", &Engine:getInstance);
then get the "engine" instance from lua:
engine.getInstance()

**Comment by mck1117** [comment]
Will that try to `delete` the object when the lua object gets GC'd?

**Comment by mck1117** [comment]
> so the only method is declare a named 'ctor' for LuaClass, for example:

looks like there's no way to do that today, then :(

**Comment by gengyong** [comment]
> > so the only method is declare a named 'ctor' for LuaClass, for example:
> 
> looks like there's no way to do that today, then :(

no ideas yet 😂 
maybe we have solution in few days.

**Comment by gengyong** [comment]
a change list was submitted to fix this issue.

so, here for singleton class:
  luaEngine.ctor("getInstance", &Engine::getInstance,  nullptr);
will define a lua constructor for 'Engine', from lua codes:
  local e  = Engine.getInstance();
got a formed Lua 'Engine' object.
the 3rd parameter 'nullptr' is destructor which will be called from GC, 
here we set it to nullptr to disable it so the singleton instance will not be destroyed.

**Comment by gengyong** [comment]
> a change list was submitted to fix this issue.
> 
> so, here for singleton class:
> luaEngine.ctor("getInstance", &Engine::getInstance, nullptr);
> will define a lua constructor for 'Engine', from lua codes:
> local e = Engine.getInstance();
> got a formed Lua 'Engine' object.
> the 3rd parameter 'nullptr' is destructor which will be called from GC,
> here we set it to nullptr to disable it so the singleton instance will not be destroyed.

@mck1117 @rusefillc

**Comment by mck1117** [comment]
that's awesome, thanks! I'll give it a try!

**Comment by gengyong** [comment]
please pull the updated version,  there are some bug fix.
