### ISSUE TITLE
Not everyone has typeid(T)

### ISSUE THREAD

**Issue by rusefillc** [gengyong/luaaa#3]
@mck1117 why exactly do we not have typeid(T) available in https://github.com/rusefi/rusefi?

Anyway we do not have typeid(T)

it would be nice to have an option not to require typeid(T) 

see rusefi current solution https://github.com/rusefi/luaaa/commit/cacdd767fb355b3b74f06a2bbd71667bc6a94baa

**Comment by gengyong** [comment]
it seems runtime type info(rtti) is disabled in your project, so typeid is
unavialiable here.

anyway we just use typeid to make friendly debug info in luaaa, so its safe
to remove it, you do a great change.

rusefillc ***@***.***>于2021年9月25日 周六08:52写道：

**Comment by gengyong** [comment]
v0.2.1: typeid() was removed if no rtti.
