### ISSUE TITLE
support struct member vars binding

### ISSUE THREAD

**Issue by srdgame** [gengyong/luaaa#34]
```cpp

struct MyCat {
	int Age;
};

void bindToLUA(lua_State * L)
{
	LuaClass<MyCat> myCat(L, "MyCat");
        myCat.ctor();
	myCat.def("Age", &MyCat::Age);
```

**Comment by gengyong** [comment]
This functionality cannot be directly implemented, and there are several reasons for it. The primary reason is that Lua and C++ object instances exist in different memory spaces. "Exporting" is merely establishing a communication mechanism between Lua and C++, where this mechanism statically defines the values and function interfaces. These interfaces are then used to communicate with the C/C++ runtime during the execution of the Lua virtual machine. However, the task of "binding struct members" involves mapping the address of C/C++ runtime objects to Lua memory space. There is no direct method for this, and even if mapped through the function interface during Lua virtual machine runtime, without defining interfaces to access relevant object methods, there is no suitable way to read and interpret it in Lua.

Furthermore, this method of mapping object addresses also introduces issues with the asynchronous lifetimes of objects in C/C++ runtime and Lua virtual machine. 

As an alternative, you can define read/write access functions for object members and then export these functions.

for example, define getter/setter functions and export them by with LuaClass, then use the setter/getter to access the member var of struct/class.

```c++
struct MyCat {
	int Age;
        int setAge(int val) {
           age = val;
           return age;
       }
     
      int getAge() const {
          return age;
      }
};

LuaClass<MyCat> myCat(L, "MyCat");
myCat.ctor();
myCat.def("setAge", &MyCat::setAge);
myCat.def("getAge", &MyCat::getAge);
```

**Comment by srdgame** [comment]
Why not hack this setter/getter in __index __newindex meta functions?

**Comment by gengyong** [comment]
new release v1.4 add new feature: export properties.
