### ISSUE TITLE
trigger event

### ISSUE THREAD

**Issue by k-i-o** [gengyong/luaaa#39]
how can i call a lua method from c++?

like emit events, for example:

C++:
void Update(){
     luaIdkBlaBla.emit("onUpdate");
} 

Lua:
func onUpdate():
    print("updated")
end

and so the lua function is called from the c++ code

**Comment by gengyong** [comment]
use lua sdk:

```cpp
    // init lua state here ...
    lua_getglobal(L, "onUpdate");
    // push params to lua stack
    lua_pushnumber(L, GetTickCount());
    // lua_pcall(L,1,1,0):  stack: 1 param in, 1 return value out
    int pcallRet = lua_pcall(L, 1, 1, 0); 
    if (pcallRet != 0) {
        printf("error %s\n", lua_tostring(L, -1));
        return -1;
    }
```

**Comment by k-i-o** [comment]
i will see if it works, wonderful
